export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";

export const GET_AUTOCOMPLETE_PRODUCTS = "GET_AUTOCOMPLETE_PRODUCS";
export const GET_AUTOCOMPLETE_SUCCESS = "GET_AUTOCOMPLETE_SUCCESS";

export const GET_PRODUCTS_FEATURED = "GET_PRODUCTS_FEATURED";
export const GET_PRODUCTS_FEATURED_SUCCESS = "GET_PRODUCTS_FEATURED_SUCCESS";

export const GET_PRODUCTS_WALLET = "GET_PRODUCTS_WALLET";
export const GET_PRODUCTS_WALLET_SUCCESS = "GET_PRODUCTS_WALLET_SUCCESS";

export const GET_PRODUCTS_LIST = "GET_PRODUCTS_LIST";
export const GET_PRODUCTS_LIST_SUCCESS = "GET_PRODUCTS_LIST_SUCCESS";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";


export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";