export const TOGGLE_NAV_DRAWER = "TOGGLE_NAV_DRAWER";
export const SET_NAV_DRAWER = "SET_NAV_DRAWER";

export const TOGGLE_AUTH_MODAL_BOX = "TOGGLE_AUTH_MODAL_BOX";
export const SET_AUTH_MODAL_BOX = "SET_AUTH_MODAL_BOX";