export const GET_ALL_ORDER = "GET_ALL_ORDER";
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS";

export const GET_USER_ORDER = "GET_USER_ORDER";
export const GET_USER_ORDER_PENDING = "GET_USER_ORDER_PENDING";
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS";

export const GET_ORDER_BY_ID = "GET_ORDER_BY_ID";
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID"; 

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";
