export const GET_CITY_LOCATION = "GET_CITY_LOCATION";
export const GET_CITY_LOCATION_SUCCESS = "GET_CITY_LOCATION_SUCCESS";
export const GET_CITY_LOCATION_FAILED = "GET_CITY_LOCATION_FAILED";

export const GET_DISTRICT_LOCATION_BY_CITY = "GET_DISTRICT_LOCATION_BY_CITY";
export const GET_DISTRICT_LOCATION_BY_CITY_SUCCESS = "GET_DISTRICT_LOCATION_BY_CITY_SUCCESS";
export const GET_DISTRICT_LOCATION_BY_CITY_FAILED = "GET_DISTRICT_LOCATION_BY_CITY_FAILED";

export const GET_WARD_LOCATION_BY_DISTRICT = "GET_WARD_LOCATION_BY_DISTRICT";
export const GET_WARD_LOCATION_BY_DISTRICT_SUCCESS = "GET_WARD_LOCATION_BY_DISTRICT_SUCCESS";
export const GET_WARD_LOCATION_BY_DISTRICT_FAILED = "GET_WARD_LOCATION_BY_DISTRICT_FAILED";

export const CLEAR_DISTRICT_LOCATION = "CLEAR_DISTRICT_LOCATION";
export const CLEAR_WARD_LOCATION = "CLEAR_WARD_LOCATION";
