export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";

export const AUTH_REFRESH_USER = "AUTH_REFRESH_USER";
export const AUTH_REFRESH_USER_SUCCESS = "AUTH_REFRESH_USER_SUCCESS";