export const GET_ALL_CART = 'GET_ALL_CART';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';

export const INCREASE_QUANTITY_CART_ITEM = 'INCREASE_QUANTITY_CART_ITEM';
export const DECREASE_QUANTITY_CART_ITEM = 'DECREASE_QUANTITY_CART_ITEM';
export const SET_QUANTITY_CART_ITEM = 'SET_QUANTITY_CART_ITEM';

export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_CART_ITEM_PENDING = 'REMOVE_CART_ITEM_PENDING';
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';

export const CLEAR_CART = 'CLEAR_CART';